Some changes
alissens/Daily-goals pull request #3
Opened 2023-02-12 06:47 UTC by kishnel

2023-02-22 16:04 UTC, alissens commented on DailyGoals/DailyGoals/AddMemberView.swift
> +	var body: some View {
spacing needs fixing here

2023-02-22 16:05 UTC, alissens requested changes
Why does it feel like the spacing is just off in all the changes?

2023-02-22 16:06 UTC, alissens commented on DailyGoals/DailyGoals/Extensions/Array+NSItemProvider.swift
> +			_ = provider.loadObject(ofClass: URL.self) { object, error in
let's make discardable?

2023-02-22 16:10 UTC, alissens commented
Could you also provide descriptions on your PRs? I can't follow all the changes. 

For example, why icon if no members are found? Why have unknown goal? Our goals are never unknown. 

Things like that.

2023-02-22 19:38 UTC, kishnel commented on DailyGoals/DailyGoals/AddMemberView.swift
> +	var body: some View {
You mean the indentation?

2023-02-22 19:42 UTC, kishnel commented on DailyGoals/DailyGoals/Extensions/Array+NSItemProvider.swift
> +			_ = provider.loadObject(ofClass: URL.self) { object, error in
loadObject is owned by Apple unfortunately, not our stuff

2023-03-06 11:47 UTC, alissens commented on DailyGoals/DailyGoals/AddMemberView.swift
> +	var body: some View {
yeah

2023-03-06 11:48 UTC, alissens approved these changes

2023-03-06 11:48 UTC, merged